version: "3"

services:

  postgres:
    image: "postgres:14"
    container_name: "postgres-service"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_DB=companies"

  java-app:
    build: "./"
    container_name: "java-spring-app"
    ports:
      #mapping 8080 system port to 8080 container port
      - "8080:8080"