spring:
  jpa:

    hibernate:

      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

      ddl-auto: create

    generate-ddl: true

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect


  datasource:
    url: 'jdbc:postgresql://postgres:5432/companies'
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver


application:
  api-key: "098eb240-6f7f-4b40-8a13-48e3d1432361"

local:
  server:
    port: 15